### PR TITLE
ideas/create-edit: remove console error with virtualizedlist and make…

### LINKED ISSUE #189: error: VirtualizedLists should never be nested in plain ScrollViews
**URL:** 
**user:** 
**expected behaviour:** Clicking on category dropdown (edit idea) should open without error
**behaviour:** Clicking on category dropdown shows error (see screenshot)
**important screensize:**
**device & browser:** 
**Comment/Question:** 

Screenshot?
Bildschirmfoto 2021-12-28 um 12 08 26

### PR DESCRIPTION
**Pull request by khamui**
… scrolling working

closes #189

### CODE REVIEW

File: components/formFields.js [hunk 1]
```diff
@@ -5,6 +5,10 @@ import DropDownPicker from 'react-native-dropdown-picker';
 import { styles } from './formFields.styles';
 import { TextSourceSans } from './TextSourceSans';
 
+// Setting list mode to scrollview globally
+// FIXME: to be checked if we want this
+DropDownPicker.setListMode('SCROLLVIEW');
```
Comment (phillimorland) [inline components/formFields.js:10]: why do we want to check this?

File: components/VirtualScrollView.js [hunk 2]
```diff
@@ -0,0 +1,18 @@
...
+import {FlatList} from 'react-native';
+
+export const VirtualScrollView = props => {
+  return (
+    <FlatList
+      style={props.style}
+      contentContainerStyle={props.contentContainerStyle}
+      data={[]}
+      ListEmptyComponent={null}
+      keyExtractor={() => 'dummy'}
```
Comment (phillimorland) [inline components/VirtualScrollView.js:11]: @khamui what does the dummy thing do?

**Review by phillimorland — APPROVED** [review]
very nice! :)

File: components/VirtualScrollView.js (hunk 2 above)
Comment (khamui) [reply components/VirtualScrollView.js:11]: oh just saw this now @phillimorland , because we don't have any data this keyExtractor does nothing here.

File: components/formFields.js (hunk 1 above)
Comment (khamui) [reply components/formFields.js:10]: Because its set globally, meaning all DropDownPicker will be affected. Maybe what we want anyway?

File: components/VirtualScrollView.js (hunk 2 above)
Comment (phillimorland) [reply components/VirtualScrollView.js:11]: danke :)

File: components/formFields.js (hunk 1 above)
Comment (phillimorland) [reply components/formFields.js:10]: I guess we'll know more when we know what else we will build for the app, I think for now it's fine and we can keep the fixme in there to not forget about it
